### PR TITLE
Remove unused import

### PR DESCRIPTION
**Pull request by Danmark**

### CODE REVIEW

**Comment by knorrie** [comment]
Sorry, but this doesn't make sense. But, thanks for the reminder that we should clean up a bunch of things here and just run them with python3 instead of 2.

**Comment by Danmark** [comment]
This is what made it run on my machine.
But I've looked into it, and it doesn't make sense to me either. :)

**Comment by knorrie** [comment]
What was the error when it didn't run?

On python 2, it changes the behavior of print to make it python 3 style compatible, (it's not used explicitely, but checkers like flake8 do not complain about it), and with python 3 it just doesn't do anything.

**Comment by Danmark** [comment]
Turns out Python 2.4.3 is really old :)
`from __future__ import print_function` works on 2.6+ as far as i can see

**Comment by knorrie** [comment]
Ah yes, all code in here assumes at least 2.7 or 3+

If you use that old (or any 2 without the future import) and do a print("something"), then the parentheses are part of grouping things in an expression,like print 3*(1+5) and not part of a function call. ;-]

**Pull request closed without merging**
